process.env.DATABASE_URL = 'postgres://test:test@localhost:5433/financeapp_test'
process.env.JWT_SECRET = 'supersecretjwtkeyatleast32chars!!'
process.env.PORT = '3000'
process.env.CORS_ORIGIN = '*'
process.env.NODE_ENV = 'test'
