name: Monorepo Split

on:
  push:
    branches:
      - main
      - develop
      - staging
      - feature/**
      - hotfix/**

permissions:
  contents: write

jobs:
  split:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - dir: web
            repo: andreluke/WebControleFinanceiro
          - dir: api
            repo: andreluke/ApiControleFinanceiro
          - dir: mobile
            repo: andreluke/MobileControleFinanceiro

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create split branch
        run: |
          git subtree split --prefix=${{ matrix.dir }} -b split-${{ matrix.dir }}

      - name: Push to target repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}

          git remote add target https://x-access-token:${GH_TOKEN}@github.com/${{ matrix.repo }}.git

          git push target split-${{ matrix.dir }}:$BRANCH --force

      - name: Test token access
        env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
            curl -H "Authorization: token $GH_TOKEN" https://api.github.com/user