name: Monorepo Split

on:
  push:
    branches:
      - main
      - develop
      - staging
      - feature/**
      - hotfix/**

permissions:
  contents: write

jobs:
  split:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - dir: web
            repo: andreluke/WebControleFinanceiro
          - dir: api
            repo: andreluke/ApiControleFinanceiro
          - dir: mobile
            repo: andreluke/MobileControleFinanceiro

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create split branch
        run: |
          git subtree split --prefix=${{ matrix.dir }} -b split-${{ matrix.dir }}

      - name: Test token access
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -H "Authorization: token $GH_TOKEN" https://api.github.com/user

      - name: Push to target repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}

          # Remove todos os extraheaders injetados pelo actions/checkout
          git config --global --unset-all http.https://github.com/.extraheader || true
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --local --unset-all http.extraheader || true

          # Define o token correto sem quebra de linha no base64
          B64_TOKEN=$(echo -n "x-access-token:${GH_TOKEN}" | base64 -w 0)
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic ${B64_TOKEN}"

          git remote set-url origin https://github.com/${{ matrix.repo }}.git

          git push origin split-${{ matrix.dir }}:$BRANCH --forcee